# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agilent86142b.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Agilent86142B(object):
    def setupUi(self, Agilent86142B):
        Agilent86142B.setObjectName("Agilent86142B")
        Agilent86142B.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(Agilent86142B)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonAutoAlign = QtWidgets.QPushButton(Agilent86142B)
        self.buttonAutoAlign.setObjectName("buttonAutoAlign")
        self.gridLayout.addWidget(self.buttonAutoAlign, 8, 1, 1, 1)
        self.subButtonLayout = QtWidgets.QVBoxLayout()
        self.subButtonLayout.setObjectName("subButtonLayout")
        self.gridLayout.addLayout(self.subButtonLayout, 2, 3, 2, 1)
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttonLayout.setObjectName("buttonLayout")
        self.buttonWavelength = QtWidgets.QPushButton(Agilent86142B)
        self.buttonWavelength.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonWavelength.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonWavelength.setObjectName("buttonWavelength")
        self.buttonLayout.addWidget(self.buttonWavelength)
        self.buttonAmplitude = QtWidgets.QPushButton(Agilent86142B)
        self.buttonAmplitude.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonAmplitude.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonAmplitude.setObjectName("buttonAmplitude")
        self.buttonLayout.addWidget(self.buttonAmplitude)
        self.buttonMarkers = QtWidgets.QPushButton(Agilent86142B)
        self.buttonMarkers.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonMarkers.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonMarkers.setObjectName("buttonMarkers")
        self.buttonLayout.addWidget(self.buttonMarkers)
        self.buttonTraces = QtWidgets.QPushButton(Agilent86142B)
        self.buttonTraces.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonTraces.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonTraces.setObjectName("buttonTraces")
        self.buttonLayout.addWidget(self.buttonTraces)
        self.buttonBW = QtWidgets.QPushButton(Agilent86142B)
        self.buttonBW.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonBW.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonBW.setAutoFillBackground(False)
        self.buttonBW.setCheckable(False)
        self.buttonBW.setFlat(False)
        self.buttonBW.setObjectName("buttonBW")
        self.buttonLayout.addWidget(self.buttonBW)
        self.buttonSystem = QtWidgets.QPushButton(Agilent86142B)
        self.buttonSystem.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonSystem.setMaximumSize(QtCore.QSize(150, 16777215))
        self.buttonSystem.setObjectName("buttonSystem")
        self.buttonLayout.addWidget(self.buttonSystem)
        self.gridLayout.addLayout(self.buttonLayout, 2, 4, 2, 1)
        self.graphLayout = QtWidgets.QGridLayout()
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")
        self.gridLayout.addLayout(self.graphLayout, 2, 0, 2, 3)
        self.topTextLayout = QtWidgets.QGridLayout()
        self.topTextLayout.setObjectName("topTextLayout")
        self.topLabel13 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel13.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel13.setObjectName("topLabel13")
        self.topTextLayout.addWidget(self.topLabel13, 2, 0, 1, 1)
        self.topLabel51 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel51.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel51.setObjectName("topLabel51")
        self.topTextLayout.addWidget(self.topLabel51, 0, 4, 1, 1)
        self.topLabel31 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel31.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel31.setObjectName("topLabel31")
        self.topTextLayout.addWidget(self.topLabel31, 0, 2, 1, 1)
        self.topLabel21 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel21.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel21.setObjectName("topLabel21")
        self.topTextLayout.addWidget(self.topLabel21, 0, 1, 1, 1)
        self.topLabel11 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel11.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel11.setObjectName("topLabel11")
        self.topTextLayout.addWidget(self.topLabel11, 0, 0, 1, 1)
        self.topLabel41 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel41.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel41.setObjectName("topLabel41")
        self.topTextLayout.addWidget(self.topLabel41, 0, 3, 1, 1)
        self.topLabel12 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel12.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel12.setObjectName("topLabel12")
        self.topTextLayout.addWidget(self.topLabel12, 1, 0, 1, 1)
        self.topLabel61 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel61.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel61.setObjectName("topLabel61")
        self.topTextLayout.addWidget(self.topLabel61, 0, 5, 1, 1)
        self.topLabel22 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel22.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel22.setObjectName("topLabel22")
        self.topTextLayout.addWidget(self.topLabel22, 1, 1, 1, 1)
        self.topLabel23 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel23.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel23.setObjectName("topLabel23")
        self.topTextLayout.addWidget(self.topLabel23, 2, 1, 1, 1)
        self.topLabel32 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel32.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel32.setObjectName("topLabel32")
        self.topTextLayout.addWidget(self.topLabel32, 1, 2, 1, 1)
        self.topLabel42 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel42.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel42.setObjectName("topLabel42")
        self.topTextLayout.addWidget(self.topLabel42, 1, 3, 1, 1)
        self.topLabel52 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel52.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel52.setObjectName("topLabel52")
        self.topTextLayout.addWidget(self.topLabel52, 1, 4, 1, 1)
        self.topLabel62 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel62.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel62.setObjectName("topLabel62")
        self.topTextLayout.addWidget(self.topLabel62, 1, 5, 1, 1)
        self.topLabel33 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel33.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel33.setObjectName("topLabel33")
        self.topTextLayout.addWidget(self.topLabel33, 2, 2, 1, 1)
        self.topLabel43 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel43.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel43.setObjectName("topLabel43")
        self.topTextLayout.addWidget(self.topLabel43, 2, 3, 1, 1)
        self.topLabel53 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel53.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel53.setObjectName("topLabel53")
        self.topTextLayout.addWidget(self.topLabel53, 2, 4, 1, 1)
        self.topLabel63 = QtWidgets.QLabel(Agilent86142B)
        self.topLabel63.setAlignment(QtCore.Qt.AlignCenter)
        self.topLabel63.setObjectName("topLabel63")
        self.topTextLayout.addWidget(self.topLabel63, 2, 5, 1, 1)
        self.gridLayout.addLayout(self.topTextLayout, 0, 0, 1, 3)
        self.buttonAutoMeasure = QtWidgets.QPushButton(Agilent86142B)
        self.buttonAutoMeasure.setObjectName("buttonAutoMeasure")
        self.gridLayout.addWidget(self.buttonAutoMeasure, 8, 0, 1, 1)
        self.bottomTextLayout = QtWidgets.QGridLayout()
        self.bottomTextLayout.setObjectName("bottomTextLayout")
        self.btmLabel12 = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btmLabel12.setFont(font)
        self.btmLabel12.setObjectName("btmLabel12")
        self.bottomTextLayout.addWidget(self.btmLabel12, 1, 0, 1, 1)
        self.btmLabel42 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btmLabel42.setObjectName("btmLabel42")
        self.bottomTextLayout.addWidget(self.btmLabel42, 1, 3, 1, 1)
        self.btmLabel32 = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btmLabel32.setFont(font)
        self.btmLabel32.setObjectName("btmLabel32")
        self.bottomTextLayout.addWidget(self.btmLabel32, 1, 2, 1, 1)
        self.btmLabel21 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btmLabel21.setObjectName("btmLabel21")
        self.bottomTextLayout.addWidget(self.btmLabel21, 0, 1, 1, 1)
        self.btmLabel11 = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btmLabel11.setFont(font)
        self.btmLabel11.setObjectName("btmLabel11")
        self.bottomTextLayout.addWidget(self.btmLabel11, 0, 0, 1, 1)
        self.btmLabel22 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btmLabel22.setObjectName("btmLabel22")
        self.bottomTextLayout.addWidget(self.btmLabel22, 1, 1, 1, 1)
        self.btmLabel52 = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btmLabel52.setFont(font)
        self.btmLabel52.setObjectName("btmLabel52")
        self.bottomTextLayout.addWidget(self.btmLabel52, 1, 4, 1, 1)
        self.btmLabel62 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel62.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btmLabel62.setObjectName("btmLabel62")
        self.bottomTextLayout.addWidget(self.btmLabel62, 1, 5, 1, 1)
        self.btmLabel31 = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btmLabel31.setFont(font)
        self.btmLabel31.setObjectName("btmLabel31")
        self.bottomTextLayout.addWidget(self.btmLabel31, 0, 2, 1, 1)
        self.btmLabel41 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btmLabel41.setObjectName("btmLabel41")
        self.bottomTextLayout.addWidget(self.btmLabel41, 0, 3, 1, 1)
        self.btmLabel61 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel61.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btmLabel61.setObjectName("btmLabel61")
        self.bottomTextLayout.addWidget(self.btmLabel61, 0, 5, 1, 1)
        self.btmLabel51 = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btmLabel51.setFont(font)
        self.btmLabel51.setObjectName("btmLabel51")
        self.bottomTextLayout.addWidget(self.btmLabel51, 0, 4, 1, 1)
        self.btmLabel71 = QtWidgets.QLabel(Agilent86142B)
        self.btmLabel71.setObjectName("btmLabel71")
        self.bottomTextLayout.addWidget(self.btmLabel71, 0, 6, 1, 1)
        self.gridLayout.addLayout(self.bottomTextLayout, 6, 0, 1, 3)
        self.line = QtWidgets.QFrame(Agilent86142B)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelActMkr = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelActMkr.setFont(font)
        self.labelActMkr.setAlignment(QtCore.Qt.AlignCenter)
        self.labelActMkr.setObjectName("labelActMkr")
        self.gridLayout_2.addWidget(self.labelActMkr, 0, 0, 1, 1)
        self.labelActTrc = QtWidgets.QLabel(Agilent86142B)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelActTrc.setFont(font)
        self.labelActTrc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelActTrc.setObjectName("labelActTrc")
        self.gridLayout_2.addWidget(self.labelActTrc, 0, 1, 1, 1)
        self.buttonActMkrGbl = QtWidgets.QPushButton(Agilent86142B)
        self.buttonActMkrGbl.setObjectName("buttonActMkrGbl")
        self.gridLayout_2.addWidget(self.buttonActMkrGbl, 1, 0, 1, 1)
        self.buttonActTrcGbl = QtWidgets.QPushButton(Agilent86142B)
        self.buttonActTrcGbl.setObjectName("buttonActTrcGbl")
        self.gridLayout_2.addWidget(self.buttonActTrcGbl, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 3, 1, 2)
        self.line_2 = QtWidgets.QFrame(Agilent86142B)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.buttonDispDisable = QtWidgets.QPushButton(Agilent86142B)
        self.buttonDispDisable.setObjectName("buttonDispDisable")
        self.gridLayout.addWidget(self.buttonDispDisable, 8, 4, 1, 1)
        self.labelDisable = QtWidgets.QLabel(Agilent86142B)
        self.labelDisable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDisable.setObjectName("labelDisable")
        self.gridLayout.addWidget(self.labelDisable, 8, 3, 1, 1)
        self.buttonSync = QtWidgets.QPushButton(Agilent86142B)
        self.buttonSync.setObjectName("buttonSync")
        self.gridLayout.addWidget(self.buttonSync, 8, 2, 1, 1)

        self.retranslateUi(Agilent86142B)
        QtCore.QMetaObject.connectSlotsByName(Agilent86142B)

    def retranslateUi(self, Agilent86142B):
        _translate = QtCore.QCoreApplication.translate
        Agilent86142B.setWindowTitle(_translate("Agilent86142B", "Form"))
        self.buttonAutoAlign.setText(_translate("Agilent86142B", "Auto Align"))
        self.buttonWavelength.setText(_translate("Agilent86142B", "Wavelength"))
        self.buttonAmplitude.setText(_translate("Agilent86142B", "Amplitude"))
        self.buttonMarkers.setText(_translate("Agilent86142B", "Markers"))
        self.buttonTraces.setText(_translate("Agilent86142B", "Traces"))
        self.buttonBW.setText(_translate("Agilent86142B", "Bandwidth/\n"
"Sweep"))
        self.buttonSystem.setText(_translate("Agilent86142B", "System"))
        self.topLabel13.setText(_translate("Agilent86142B", ""))
        self.topLabel51.setText(_translate("Agilent86142B", ""))
        self.topLabel31.setText(_translate("Agilent86142B", ""))
        self.topLabel21.setText(_translate("Agilent86142B", ""))
        self.topLabel11.setText(_translate("Agilent86142B", ""))
        self.topLabel41.setText(_translate("Agilent86142B", ""))
        self.topLabel12.setText(_translate("Agilent86142B", ""))
        self.topLabel61.setText(_translate("Agilent86142B", ""))
        self.topLabel22.setText(_translate("Agilent86142B", ""))
        self.topLabel23.setText(_translate("Agilent86142B", ""))
        self.topLabel32.setText(_translate("Agilent86142B", ""))
        self.topLabel42.setText(_translate("Agilent86142B", ""))
        self.topLabel52.setText(_translate("Agilent86142B", ""))
        self.topLabel62.setText(_translate("Agilent86142B", ""))
        self.topLabel33.setText(_translate("Agilent86142B", ""))
        self.topLabel43.setText(_translate("Agilent86142B", ""))
        self.topLabel53.setText(_translate("Agilent86142B", ""))
        self.topLabel63.setText(_translate("Agilent86142B", ""))
        self.buttonAutoMeasure.setText(_translate("Agilent86142B", "Auto Measure"))
        self.btmLabel12.setText(_translate("Agilent86142B", "VBW:"))
        self.btmLabel42.setText(_translate("Agilent86142B", ""))
        self.btmLabel32.setText(_translate("Agilent86142B", "ST:"))
        self.btmLabel21.setText(_translate("Agilent86142B", ""))
        self.btmLabel11.setText(_translate("Agilent86142B", "RBW:"))
        self.btmLabel22.setText(_translate("Agilent86142B", ""))
        self.btmLabel52.setText(_translate("Agilent86142B", "Avg:"))
        self.btmLabel62.setText(_translate("Agilent86142B", ""))
        self.btmLabel31.setText(_translate("Agilent86142B", "Sens:"))
        self.btmLabel41.setText(_translate("Agilent86142B", ""))
        self.btmLabel61.setText(_translate("Agilent86142B", ""))
        self.btmLabel51.setText(_translate("Agilent86142B", "Integ:"))
        self.btmLabel71.setText(_translate("Agilent86142B", ""))
        self.labelActMkr.setText(_translate("Agilent86142B", "Active Marker:"))
        self.labelActTrc.setText(_translate("Agilent86142B", "Active Trace:"))
        self.buttonActMkrGbl.setText(_translate("Agilent86142B", "PushButton"))
        self.buttonActTrcGbl.setText(_translate("Agilent86142B", "PushButton"))
        self.buttonDispDisable.setText(_translate("Agilent86142B", "PushButton"))
        self.labelDisable.setText(_translate("Agilent86142B", "Display:"))
        self.buttonSync.setText(_translate("Agilent86142B", "Device Sync"))

