# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systemwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_systemWindow(object):
    def setupUi(self, systemWindow):
        systemWindow.setObjectName("systemWindow")
        systemWindow.resize(500, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(systemWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(systemWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.tabHelp = QtWidgets.QWidget()
        self.tabHelp.setObjectName("tabHelp")
        self.gridLayout = QtWidgets.QGridLayout(self.tabHelp)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tabHelp)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.firmwareLabel = QtWidgets.QLabel(self.tabHelp)
        self.firmwareLabel.setText("")
        self.firmwareLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.firmwareLabel.setObjectName("firmwareLabel")
        self.gridLayout.addWidget(self.firmwareLabel, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabHelp, "")
        self.tabPowCal = QtWidgets.QWidget()
        self.tabPowCal.setObjectName("tabPowCal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabPowCal)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelFacPowCal = QtWidgets.QLabel(self.tabPowCal)
        self.labelFacPowCal.setObjectName("labelFacPowCal")
        self.gridLayout_2.addWidget(self.labelFacPowCal, 1, 1, 1, 1)
        self.labelUserPowCal = QtWidgets.QLabel(self.tabPowCal)
        self.labelUserPowCal.setObjectName("labelUserPowCal")
        self.gridLayout_2.addWidget(self.labelUserPowCal, 2, 1, 1, 1)
        self.lineCalWL = QtWidgets.QLineEdit(self.tabPowCal)
        self.lineCalWL.setObjectName("lineCalWL")
        self.gridLayout_2.addWidget(self.lineCalWL, 4, 1, 1, 1)
        self.lineCalPower = QtWidgets.QLineEdit(self.tabPowCal)
        self.lineCalPower.setObjectName("lineCalPower")
        self.gridLayout_2.addWidget(self.lineCalPower, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tabPowCal)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabPowCal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tabPowCal)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabPowCal)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabPowCal)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tabPowCal)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tabPowCal)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tabPowCal, "")
        self.tabWLCal = QtWidgets.QWidget()
        self.tabWLCal.setObjectName("tabWLCal")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabWLCal)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.tabWLCal)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tabWLCal)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tabWLCal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.tabWLCal)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.labelUserWLCal = QtWidgets.QLabel(self.tabWLCal)
        self.labelUserWLCal.setObjectName("labelUserWLCal")
        self.gridLayout_3.addWidget(self.labelUserWLCal, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tabWLCal)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 2)
        self.labelFacWLCal = QtWidgets.QLabel(self.tabWLCal)
        self.labelFacWLCal.setObjectName("labelFacWLCal")
        self.gridLayout_3.addWidget(self.labelFacWLCal, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tabWLCal)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 0, 1, 1)
        self.lineSetCalWL = QtWidgets.QLineEdit(self.tabWLCal)
        self.lineSetCalWL.setObjectName("lineSetCalWL")
        self.gridLayout_3.addWidget(self.lineSetCalWL, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tabWLCal)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 2, 1, 1)
        self.buttonSigSource = QtWidgets.QPushButton(self.tabWLCal)
        self.buttonSigSource.setObjectName("buttonSigSource")
        self.gridLayout_3.addWidget(self.buttonSigSource, 3, 2, 1, 1)
        self.buttonWLRef = QtWidgets.QPushButton(self.tabWLCal)
        self.buttonWLRef.setObjectName("buttonWLRef")
        self.gridLayout_3.addWidget(self.buttonWLRef, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tabWLCal, "")
        self.tabDisp = QtWidgets.QWidget()
        self.tabDisp.setObjectName("tabDisp")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabDisp)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineIncrement = QtWidgets.QLineEdit(self.tabDisp)
        self.lineIncrement.setObjectName("lineIncrement")
        self.gridLayout_4.addWidget(self.lineIncrement, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tabDisp)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDisp, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(systemWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(systemWindow)
        self.tabWidget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(systemWindow.accept)
        self.buttonBox.rejected.connect(systemWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(systemWindow)

    def retranslateUi(self, systemWindow):
        _translate = QtCore.QCoreApplication.translate
        systemWindow.setWindowTitle(_translate("systemWindow", "System Settings"))
        self.label.setText(_translate("systemWindow", "Firmware:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("systemWindow", "Help"))
        self.labelFacPowCal.setText(_translate("systemWindow", "TextLabel"))
        self.labelUserPowCal.setText(_translate("systemWindow", "TextLabel"))
        self.label_8.setText(_translate("systemWindow", "Set Calibration Wavelength:"))
        self.label_2.setText(_translate("systemWindow", "Power Calibration Setup"))
        self.label_3.setText(_translate("systemWindow", "Factory Power Cal Date:"))
        self.label_7.setText(_translate("systemWindow", "Set Calibration Power:"))
        self.label_4.setText(_translate("systemWindow", "User Power Cal Date:"))
        self.label_5.setText(_translate("systemWindow", "dBm"))
        self.label_6.setText(_translate("systemWindow", "nm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPowCal), _translate("systemWindow", "Power Calibration"))
        self.label_12.setText(_translate("systemWindow", "Signal Sourse:"))
        self.label_10.setText(_translate("systemWindow", "Factory Wavelength Cal Date:"))
        self.label_9.setText(_translate("systemWindow", "Wavelength Calibration Setup"))
        self.label_13.setText(_translate("systemWindow", "Wavelengths Referenced In:"))
        self.labelUserWLCal.setText(_translate("systemWindow", "TextLabel"))
        self.label_11.setText(_translate("systemWindow", "User Wavelength Cal Date:"))
        self.labelFacWLCal.setText(_translate("systemWindow", "TextLabel"))
        self.label_14.setText(_translate("systemWindow", "Set Calibration Wavelength:"))
        self.label_15.setText(_translate("systemWindow", "nm"))
        self.buttonSigSource.setText(_translate("systemWindow", "PushButton"))
        self.buttonWLRef.setText(_translate("systemWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWLCal), _translate("systemWindow", "Wavelength Calibration"))
        self.label_16.setText(_translate("systemWindow", "Marker Step Increment:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDisp), _translate("systemWindow", "Display"))

